# Generated by Django 4.1.3 on 2023-07-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("photo_count", models.IntegerField(default=0, editable=False)),
                ("url_slug", models.SlugField(blank=True, unique=True)),
                (
                    "photos",
                    models.ManyToManyField(
                        related_name="album", to="mediamanager.photo"
                    ),
                ),
                ("speltak", models.ManyToManyField(blank=True, to="base.speltak")),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="thumbnail_of_album",
                        to="mediamanager.photo",
                    ),
                ),
            ],
        ),
    ]
