# Generated by Django 4.1.3 on 2023-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediamanager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speltak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="speltak",
            field=models.ManyToManyField(
                blank=True, null=True, to="mediamanager.speltak"
            ),
        ),
    ]
