# Generated by Django 4.1.3 on 2023-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediamanager", "0002_speltak_album_speltak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="speltak",
            field=models.ManyToManyField(blank=True, to="mediamanager.speltak"),
        ),
    ]
