# Generated by Django 4.1.3 on 2023-06-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediamanager", "0003_alter_album_speltak"),
    ]

    operations = [
        migrations.AddField(
            model_name="album", name="foto_count", field=models.IntegerField(default=0),
        ),
    ]
