# Generated by Django 4.1.3 on 2023-06-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediamanager", "0004_album_foto_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="")),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="album",
            name="foto_count",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
