# Generated by Django 4.1.3 on 2023-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediamanager", "0005_photo_alter_album_foto_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="url_slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
